// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myremvsgkoiyzkxhjmlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cmVtdnNna29peXpreGhqbWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTQxODksImV4cCI6MjA2MzQ5MDE4OX0.H89u5R9hVJX1zjJ8L7eqylfd33H43pjLRd8Okyh2DGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);